module.exports = [
  { path: '/' },
  { path: '/login' },
  { path: '/register' },
  { path: '/resetPassword' },
  { path: '/product/categroy' },
  { path: '/product/categroyAdd' },
  { path: '/product/categroyEdit' },
  { path: '/product/categroyView' },
  { path: '/product'},
  { path: '/product/productAdd' },
  { path: '/product/productEdit' },
  { path: '/product/productView' },
  { path: '/product/tag' },
  { path: '/product/trial' },
  { path: '/product/trialAdd' },
  { path: '/product/trialEdit' },
  { path: '/product/trialView' },
  { path: '/product/evaluate' },
  { path: '/product/evaluateView'},
  { path: '/product/freight' },
  { path: '/product/freightAdd' },
  { path: '/product/freightEdit' },
  { path: '/product/freightView' },
  { path: '/product/brand' },
  { path: '/order/online'},
  { path: '/order/orderView' },
  { path: '/order/offline'},
  { path: '/order/refund'},
  { path: '/order/trialApplication'},
  { path: '/order/setExpress' },
  { path:'/store' },
  { path: '/store/addStore' },
  { path: '/store/editStore' },
  { path: '/store/viewStore' },
  { path: '/supply/warehouse' },
  { path: '/supply/warehouseAdd' },
  { path: '/supply/warehouseEdit' },
  { path: '/supply/warehouseView' },
  { path: '/supply/purchaseOrder'},
  { path: '/supply/purchaseOrderAdd'},
  { path: '/supply/purchaseOrderEdit'},
  { path: '/supply/purchaseOrderView'},
  { path: '/supply/purchaseReturn'},
  { path: '/supply/purchaseReturnAdd'},
  { path: '/supply/purchaseReturnEdit'},
  { path: '/supply/purchaseReturnView'},
  { path: '/supply/putStorageAdd'},
  { path: '/supply/putStorageEdit'},
  { path: '/supply/putStorageView'},
  { path: '/supply/putStorage'},
  { path: '/supply/outStorage'},
  { path: '/supply/outStorageAdd'},
  { path: '/supply/outStorageEdit'},
  { path: '/supply/outStorageView'},
  { path: '/supply/transfer'},
  { path: '/supply/transferAdd'},
  { path: '/supply/transferEdit'},
  { path: '/supply/transferView'},
  { path: '/supply/inventory'},
  { path: '/supply/inventoryAdd'},
  { path: '/supply/inventoryEdit'},
  { path: '/supply/inventoryView'},
  { path: '/supply/goodsHub'},
  { path: '/supply/goodsHubAdd'},
  { path: '/supply/goodsHubEdit'},
  { path: '/supply/goodsHubView'},
  { path: '/supply/goods'},
  { path: '/supply/goodsAdd'},
  { path: '/supply/goodsEdit'},
  { path: '/supply/goodsView'},
  { path: '/supply/goodsCategroy'},
  { path: '/supply/distributor'},
  { path: '/supply/distributorAdd'},
  { path: '/supply/distributorEdit'},
  { path: '/supply/distributorView'},
  { path: '/sys/rule' },
  { path: '/sys/adGroup'},
  { path: '/sys/adGroupView'},
  { path: '/sys/advertising'},
  { path: '/sys/wechatTemplate' },
  { path: '/sys/wechatTemplateAdd'},
  { path: '/sys/wechatTemplateEdit'},
  { path: '/sys/wechatTemplateView'},
  { path: '/sys/user'},
  { path: '/sys/userView'},
  { path: '/sys/autoReplay'},
  { path: '/sys/printer'},
  { path: '/config/mall' },
  { path: '/config/wechat'},
  { path: '/config/alipay'},
  { path: '/config/goods'},
  { path: '/config/coupon'},
  { path: '/config/mallLink'},
  { path: '/config/smallProgram'},
  { path: '/config/internalSys'},
  { path: '/config/print'},
  { path: '/config/other'},
  { path: '/marketing/plan'},
  { path: '/marketing/couponUsage'},
  { path: '/marketing/couponTemplate'},
  { path: '/marketing/couponTemplateAdd'},
  { path: '/notice'},
  { path: '/notice/noticeAdd'},
  { path: '/notice/noticeEdit'}
]
