module.exports = [
  { path: '/' },
  { path: '/login' },
  { path: '/register' },
  { path: '/resetPassword' },
  { path: '/product/categroy' },
  { path: '/product/categroyAdd' },
  { path: '/product/categroyEdit' },
  { path: '/product/categroyView' },
  { path: '/product'},
  { path: '/product/productAdd' },
  { path: '/product/productEdit' },
  { path: '/product/productView' },
  { path: '/product/tag' },
  { path: '/product/trial' },
  { path: '/product/trialAdd' },
  { path: '/product/trialEdit' },
  { path: '/product/trialView' },
  { path: '/product/evaluate' },
  { path: '/product/freight' },
  { path: '/product/freightAdd' },
  { path: '/product/freightEdit' },
  { path: '/product/freightView' },
  { path: '/product/brand' },
  { path: '/order/online'},
  { path: '/order/orderView' },
  { path: '/order/offline'},
  { path: '/order/refund'},
  { path: '/order/trialApplication'},
  { path: '/order/setExpress' },
  { path:'/store' },
  { path: '/store/addStore' },
  { path: '/store/editStore' },
  { path: '/store/viewStore' },
  { path: '/supply/warehouse' },
  { path: '/supply/warehouseAdd' },
  { path: '/supply/warehouseEdit' },
  { path: '/supply/warehouseView' },
  { path: '/sys/rule' },
  { path: '/sys/adGroup'},
  { path: '/sys/adGroupView'},
  { path: '/sys/advertising'},
  { path: '/sys/wechatTemplate' },
  { path: '/sys/wechatTemplateAdd'},
  { path: '/sys/wechatTemplateEdit'},
  { path: '/sys/wechatTemplateView'},
  { path: '/sys/user'},
  { path: '/sys/userView'},
  { path: '/sys/autoReplay'},
  { path: '/sys/printer'},
  { path: '/config/mall' },
  { path: '/config/wechat'},
  { path: '/config/alipay'},
  { path: '/config/goods'},
  { path: '/config/coupon'},
  { path: '/config/mallLink'},
  { path: '/config/smallProgram'},
  { path: '/config/internalSys'},
  { path: '/config/print'},
  { path: '/config/other'},
  { path: '/marketing/plan'},
  { path: '/marketing/couponUsage'},
  { path: '/marketing/couponTemplate'},
  { path: '/marketing/couponTemplateAdd'}
]
